### PR TITLE
WIP: Allow storing xnd in plasma

### LINKED ISSUE #4: Store xnd objects in plasma
We should be able to store xnd objects in the [Plasma store](https://arrow.apache.org/docs/python/plasma.html), similar to how you can store arrow memory. [In the blog post introducing Apache Arrow's usage with Plasma](https://arrow.apache.org/blog/2017/08/08/plasma-in-memory-object-store/), they outline the motivation for the store. Similar to arrow, it would be beneficial to store xnd objects, so that multiple processes on on one computer could all access them without copying or serialization.

### PR DESCRIPTION
**Pull request by saulshanabrook**
Storing xnd objects in the Plasma store will allow us to share them between multiple processes on a machine, without copying.  This pull request creates a C wrapper around plasma (`libplasma`), creates a `xndp` object in `libxnd` that stores a reference to a plasma object and a type, and exposes a Python API to create xnd objects stored in plasma.

### `libplasma`

- [ ] expose plasma client
  - [ ] create
  - [ ] get
  - [ ] create
- [ ] figure out how best to compile
- [ ] expose from/to binary for object IDs

### `libxnd`:

- [ ] add init function that creates plasma object
- [ ] add get function that retrieves object from plasma and creates `xnd` object
- [ ] compile `xndp` only when arrow is included
- [ ] rename `xndp` to `pxnd`

### Python
- [ ] create `xndp` object

Closes #4

### CODE REVIEW

**Comment by wesm** [comment]
Would you like to contribute the C API wrapper to Apache Arrow? I think we'd like to grow an official C API cc @robertnishihara @pcmoritz

**Comment by saulshanabrook** [comment]
@wesm Yeah, I am happy to develop that in Arrow instead of here.

**Comment by robertnishihara** [comment]
Seems like a good idea to me :)

**Comment by saulshanabrook** [comment]
I am moving this to it's own repo for now https://github.com/plures/pxnd. It's still very much in flux/an experiment, but once it's more stable I am happy to move out the `libplasma` part to Arrow.

**Pull request closed without merging**
